Repository dev1abhi/Flutter-Animations, pull requests merged in 2023-10, with the labels that each got.

#3 FadeIn and FadeOut animation in Flutter
  README.md
Labels: documentation, hacktoberfest-accepted, hacktoberfest

#6 added SplashScreen with LottieAnimation
  assets/FlutterAnimation.json
  lib/Screens/SplashScreen.dart
  lib/main.dart
  pubspec.yaml
Labels: enhancement, hacktoberfest-accepted, hacktoberfest

#7 Animations docs
  README.md
Labels: documentation, hacktoberfest-accepted, hacktoberfest

#12 text animation left right up down added
  lib/Controllers/drawercontroller.dart
  lib/Screens/menuscreen.dart
  lib/Text/move_udlr_screen.dart
  lib/Text/tex_screen.dart
  lib/main.dart
Labels: enhancement, hacktoberfest-accepted, hacktoberfest

#13 Added Flutter water drop effect.
  lib/Controllers/drawercontroller.dart
  lib/Screens/menuscreen.dart
  lib/Screens/water_drop_effect.dart
Labels: enhancement, hacktoberfest-accepted, hacktoberfest

#15 added a new app icon
  android/app/build.gradle
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/res/mipmap-hdpi/launcher_icon.png
  android/app/src/main/res/mipmap-mdpi/launcher_icon.png
  android/app/src/main/res/mipmap-xhdpi/launcher_icon.png
  android/app/src/main/res/mipmap-xxhdpi/launcher_icon.png
  android/app/src/main/res/mipmap-xxxhdpi/launcher_icon.png
  assets/icons/flutter_animations_icon.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-1024x1024@1x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@1x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@2x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@3x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@1x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@2x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@3x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@1x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@2x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@3x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-50x50@1x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-50x50@2x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-57x57@1x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-57x57@2x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-60x60@2x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-60x60@3x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-72x72@1x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-72x72@2x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-76x76@1x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-76x76@2x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-83.5x83.5@2x.png
  pubspec.yaml
Labels: hacktoberfest-accepted, hacktoberfest

#17 Naming convention
  lib/Screens/fade_in_fade_out.dart
  lib/Screens/homepage.dart
  lib/Screens/mainscreen.dart
  lib/Screens/menuscreen.dart
  lib/Screens/water_drop_effect.dart
  lib/Text/tex_screen.dart
  lib/helpers/colors.dart
  lib/main.dart
  lib/widgets/customAppBar.dart
Labels: enhancement, hacktoberfest-accepted, hacktoberfest

#18 bounce animations
  lib/Controllers/drawercontroller.dart
  lib/Screens/bounce_animation.dart
  lib/Screens/fade_in_fade_out.dart
  lib/Screens/mainscreen.dart
  lib/Screens/menuscreen.dart
  lib/Text/move_udlr_screen.dart
  lib/Text/tex_screen.dart
  lib/widgets/customAppBar.dart
Labels: enhancement, feature

#20 ExplicitAnimations
  lib/Controllers/drawercontroller.dart
  lib/Screens/explicit_animation.dart
  lib/Screens/menuscreen.dart
Labels: enhancement, feature

#21 FlipCounter Animation
  lib/Controllers/drawercontroller.dart
  lib/Screens/bounce_animation.dart
  lib/Screens/flip_counter.dart
  lib/Screens/menuscreen.dart
  pubspec.yaml
Labels: enhancement

#23 Animated Dialog Box Added
  lib/Controllers/drawercontroller.dart
  lib/Screens/animated_dialog.dart
  lib/Screens/menuscreen.dart
  pubspec.yaml
Labels: hacktoberfest-accepted, hacktoberfest, feature

#26 Added Loading Animation
  README.md
  lib/Controllers/drawercontroller.dart
  lib/Screens/loading_animation.dart
  lib/Screens/menuscreen.dart
Labels: enhancement, hacktoberfest-accepted, feature

#29 Added text animation docs
  README.md
  windows/runner/flutter_window.cpp
Labels: hacktoberfest-accepted, hacktoberfest

#28 Added new Animation: Colorized text
  lib/Screens/colorize_text.dart
  lib/Screens/menuscreen.dart
  lib/controllers/drawercontroller.dart
  macos/Flutter/GeneratedPluginRegistrant.swift
  pubspec.yaml
Labels: enhancement, hacktoberfest, feature

#30 Text interpolation implementation added.
  lib/Screens/menuscreen.dart
  lib/Screens/text_interpolation.dart
  lib/controllers/drawercontroller.dart
Labels: hacktoberfest-accepted, hacktoberfest, feature
